#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ComfyUI Subtitle Detector - RapidOCR Implementation
"""

from .nodes import NODE_CLASS_MAPPINGS as NODES_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY_MAPPINGS

from .eraser_node import NODE_CLASS_MAPPINGS as ERASER_MAPPINGS
from .eraser_node import NODE_DISPLAY_NAME_MAPPINGS as ERASER_DISPLAY_MAPPINGS

# 合并所有节点
NODE_CLASS_MAPPINGS = {**NODES_MAPPINGS, **ERASER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODES_DISPLAY_MAPPINGS, **ERASER_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
